# Generated by Django 5.0.2 on 2025-06-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkPrecedence', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('linkedId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contacts', to='identify.contact')),
            ],
            options={
                'db_table': 'contact',
                'indexes': [models.Index(fields=['email'], name='contact_email_7a7031_idx'), models.Index(fields=['phoneNumber'], name='contact_phoneNu_6d8c86_idx'), models.Index(fields=['linkedId'], name='contact_linkedI_8ccb73_idx')],
            },
        ),
    ]
