services:
  - type: web
    name: bitespeed
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn biteSpeed.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: bitespeed-db
          property: connectionString

databases:
  - name: bitespeed-db
    databaseName: bitespeed
    user: bitespeed 